name: Markdown to PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  converttopdf:
    name: Convert README.md to PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: .
          output_dir: output
          build_html: true

      - name: Move generated files to pdfs/
        run: |
          mkdir -p pdfs
          cp output/README.* pdfs/

      - name: Commit PDF and HTML back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: Generated README PDF and HTML"
          file_pattern: pdfs/*
