name: Markdown to PDF, HTML, DOCX

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  convert-doc:
    name: Convert README.md to multiple formats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert to PDF, HTML, DOCX
        run: |
          mkdir output
          pandoc README.md -o output/README.pdf
          pandoc README.md -o output/README.html
          pandoc README.md -o output/README.docx

      - name: Show output files
        run: ls -lh output/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: README-pdf
          path: output/README.pdf

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: README-html
          path: output/README.html

      - name: Upload DOCX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: README-docx
          path: output/README.docx
