name: Convert Markdown and Publish via GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert README.md to HTML, PDF, DOCX
        run: |
          mkdir output
          cp style.css output/
          pandoc README.md -o output/index.html \
            --standalone \
            --css=style.css \
            --metadata title="Voorstel uitstap Chevetogne"
          pandoc README.md -o output/README.pdf \
            --pdf-engine=xelatex \
            -V title="Voorstel uitstap naar Chevetogne" \
            -V mainfont="DejaVu Sans" \
            -V fontsize=12pt \
            -V geometry=margin=2.5cm \
            -V colorlinks=true \
            -V linkcolor=blue
          pandoc README.md -o output/README.docx
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
